// Downloads the GTA V atlas map tiles (the same tiles gtaservers.org/nopixel uses)
// into ./tiles/{z}/{x}/{y}.webp so the map works fully offline.
//
// Only tiles that actually exist are fetched: the site ships a bitmap of
// available tiles, which we read from its JS bundle and also save to
// ./tiles/available.js so the map never requests missing tiles.
//
// Usage: node scripts/download-tiles.mjs [--force]

import { mkdir, writeFile, access } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'tiles');
const SITE = 'https://gtaservers.org';
const TILE_SET = 'v2';
const MAX_ZOOM = 8;
const CONCURRENCY = 6;
const force = process.argv.includes('--force');

async function getBitmap() {
  const js = await (await fetch(`${SITE}/assets/stream-gate.js`)).text();
  const b64 = js.match(/="([A-Za-z0-9+/=]{2000,})"/)?.[1];
  if (!b64) throw new Error('Could not find the tile bitmap in stream-gate.js');
  return b64;
}

function hasTile(bits, z, x, y) {
  const s = 2 ** z;
  const o = (4 ** z - 1) / 3 + y * s + x;
  return (o >> 3) < bits.length && (bits[o >> 3] & (128 >> (o & 7))) !== 0;
}

async function exists(p) {
  try { await access(p); return true; } catch { return false; }
}

const b64 = await getBitmap();
const bits = Buffer.from(b64, 'base64');

const jobs = [];
for (let z = 0; z <= MAX_ZOOM; z++) {
  const s = 2 ** z;
  for (let y = 0; y < s; y++)
    for (let x = 0; x < s; x++)
      if (hasTile(bits, z, x, y)) jobs.push({ z, x, y });
}

await mkdir(OUT, { recursive: true });
await writeFile(
  join(OUT, 'available.js'),
  `// Bitmap of which tiles exist (generated by scripts/download-tiles.mjs)\nwindow.TILE_BITMAP = "${b64}";\nwindow.TILE_MAX_ZOOM = ${MAX_ZOOM};\n`
);

console.log(`${jobs.length} tiles to check (z0-${MAX_ZOOM})`);
let done = 0, fetched = 0, failed = 0;

async function worker() {
  while (jobs.length) {
    const { z, x, y } = jobs.shift();
    const file = join(OUT, String(z), String(x), `${y}.webp`);
    try {
      if (force || !(await exists(file))) {
        const res = await fetch(`${SITE}/map/tiles/${TILE_SET}/${z}/${x}/${y}.webp`);
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        await mkdir(dirname(file), { recursive: true });
        await writeFile(file, Buffer.from(await res.arrayBuffer()));
        fetched++;
      }
    } catch (err) {
      failed++;
      console.warn(`  ${z}/${x}/${y}: ${err.message}`);
    }
    if (++done % 500 === 0) console.log(`  ${done} done`);
  }
}

await Promise.all(Array.from({ length: CONCURRENCY }, worker));
console.log(`Finished: ${fetched} downloaded, ${done - fetched - failed} already present, ${failed} failed`);
